### ISSUE TITLE
Parsing app package name, version etc.

### ISSUE THREAD

**Issue by rehmatworks** [mikusjelly/apkutils#1]
Hi,
Thanks for your contribution to the community. I can't find any documentation for this script. Is there any way to retrieve package name and all other general info? If yes, then please update some examples.

**Comment by mikusjelly** [comment]
```
from apkutils.apk import APK

apk = APK('test.apk')
mf = apk.get_manifest()
pkg_name = mf['@package']
```
The `mf` is a dict.

Later I will write some examples, thanks your feedback.
