### ISSUE TITLE
Parse apk Launch Icon path

### ISSUE THREAD

**Issue by codeskyblue** [mikusjelly/apkutils#11]
Thanks for great tool. (I'm in China ^_^)

Can you give some hint about how to get icon file from apk? I can see using this lib can get string from asar file, but how to do next.

**Comment by mikusjelly** [comment]
icon定义类似于`android:icon="@0xFFFFFFFF"`，解析arsc文件得到路径，然后从APK文件中提取出来。

具体用法，自行参考测试用例 [test_arsc.py](https://github.com/mikusjelly/apkutils/blob/master/tests/test_arsc.py) ，其他方法自行看代码。
