### ISSUE TITLE
可以添加个提取图标功能吗

### ISSUE THREAD

**Issue by ohyeah521** [mikusjelly/apkutils#35]
可以添加个提取图标功能吗

**Comment by kin9-0rz** [comment]
```
APK.get_app_icons()
```

https://github.com/kin9-0rz/apkutils/blob/06fedf987ccf8b574fd2654927c5cef0ed81f877/src/apkutils/apk.py#L569

**Comment by ohyeah521** [comment]
有的apk的图标是矢量图，xml文件，这种有办法合成图标吗？
[xml.zip](https://github.com/user-attachments/files/17361163/xml.zip)

**Comment by kin9-0rz** [comment]
你是说svg的那种图么？自己网上找个库，转就好。

这个库只是通过 android:icon 这个属性来找APP的图标路径，不提供这种转换库。
