### ISSUE TITLE
Have create a py2/3 compatible fork

### ISSUE THREAD

**Issue by zhangchunlin** [mikusjelly/apkutils#8]
https://github.com/zhangchunlin/apkutils
What I have done:
- add cigam as external lib, because cigam is also only support py3
- fix print in py2
- change apkfile.py implementation, inherit from zipfile.ZipFile, and implementation 2 code because the ZipFile in py2 and py3 are so different
- use six and future to make both 2 and 3 are compatible

Because the modification is too big, and I think you may not want to make it compatible with py2, so I did not raise PR with it.

**Comment by mikusjelly** [comment]
@zhangchunlin 
I don't use PY2 a few years ago, All my projects are written in PY3.

**Comment by zhangchunlin** [comment]
Yes, but I want to use it in a py2 project which have no plan to migrate to py3, so I try to do this.

**Comment by zhangchunlin** [comment]
https://github.com/zhangchunlin/apkutils/commit/0c85d605470d35765fa754b912c1e72c0965b99d
modify the Certificate result to a list of dict, example:
```
[{'has_expired': False, 'version': 0, 'subject': {'stateOrProvinceName': None, 'commonName': 'Android Debug', 'organizationalUnitName': None, 'organizationName': 'Android', 'emailAddress': None, 'localityName': None, 'countryName': 'US'}, 'sha256_digest': 'E5:9B:0C:6D:FD:B1:A4:15:BE:C5:BC:1C:09:FD:D0:B0:75:FF:53:9A:AE:97:53:56:6C:7A:65:4A:4C:B4:B3:C1', 'serial_number': 1, 'md5_digest': 'A5:2A:A4:AC:72:91:FA:79:88:14:36:B2:F3:F1:30:2A', 'sha1_digest': 'DD:84:8D:93:CF:3D:B8:AF:CC:45:93:B8:9E:77:B6:01:20:77:AF:46', 'issuer': {'stateOrProvinceName': None, 'commonName': 'Android Debug', 'organizationalUnitName': None, 'organizationName': 'Android', 'emailAddress': None, 'localityName': None, 'countryName': 'US'}}]
```

https://github.com/zhangchunlin/apkutils/commit/acfd35e089eef7d09122ff9d964998c3ce175aa5
Add pem file support to Certificate class
